config/routes.rb
EcogwikiRuby::Application.routes.draw do

  devise_for :users, skip: [:sessions, :passwords, :registrations]
  devise_scope :user do
    get '/sign_in', to: 'users/sessions#new', as: 'sign_in'
    post '/sign_in', to: 'users/sessions#create', as: 'sign_in'
    delete '/sign_out', to: 'users/sessions#destroy', as: 'sign_out'
  end

  get '/changes', to: 'home#sp_changes', as: 'changes'
  get '/searches', to: 'home#sp_searches', as: 'searches'
  get '/preference', to: 'home#sp_preferences', as: 'preference'
  post '/preferences', to: 'home#save_sp_preferences', as: 'preference'
  post '/helper/markdown', to: 'home#sp_markdown', as: 'helper_markdown'

  get '*wikipage', to: 'home#page_handler', as: 'wikipage', wikipage: /.+/
  post '*wikipage', to: 'home#write_handler', wikipage: /.+/
  put '*wikipage', to: 'home#update_handler', wikipage: /.+/
  delete '*wikipage', to: 'home#remove_handler', wikipage: /.+/
  root :to => 'home#root_handler'

end

app/models/wikipage.rb
require 'murmurhash3'

class Wikipage < ActiveRecord::Base
  attr_accessible :title, :body, :revision, :user_id,
                  :modifier, :comment, :acl_read, :acl_write, :link_id

  has_many :tocs
  has_many :revisions
  has_many :similar_pages

  belongs_to :user

  def fill_in_default(user)
    unless user.nil?
      self.user_id = user.id
      self.modifier = user.email
    end
    self.revision = 1
    self.save
  end

  def update_wikipage(params, user)
    if params[:body].blank? || self.body == params[:body]
      return false
    end
    self.body = params[:body]
    self.comment = params[:comment] unless self.comment == params[:comment]
    self.modifier = user.email
    self.revision += 1
    unless self.save
      return false
    end
    self.generate_toc
  end

  def can_write?(user)
    return false if user.nil?
    if self.acl_write.nil?
      return false
    end
    acls = self.acl_write.split(',')
    acls.include?(user.email) || acls.include?('all')
  end

  def user_preference
    Preference.find_by_email(self.modifier)
  end

  def before_save
    revision = self.revisions.new
    revision.title = self.title
    revision.body = self.body
    revision.revision = self.revision
    revision.user_id = self.user_id
    revision.modifier = self.modifier
    revision.comment = self.comment
    revision.save
  end

  private
  def make_header_key(s)
    MurmurHash3::Native128.murmur3_128_str_hash(s).pack('L*').unpack('H*').first
  end

  def generate_toc
    body = self.body

    self.tocs.each {|t| t.destroy } unless self.tocs.nil?

    current_order = 0
    current_depth = 0
    keys = []

    body.each_line do |line|
      m = /^(#+)(\s+)(.+)/.match(line)
      next if m.nil?

      header_len = m[1].length
      raise 'Header must start with 1' if (current_depth - header_len).abs > 1
      current_depth = header_len
      title = m[3]
      key = make_header_key(title)
      until keys.include?(key) do
        key = make_header_key(title + Random.rand(10000).to_s)
        keys.append(key) unless keys.include?(key)
      end

      depth = header_len
      order = current_order
      toc = self.tocs.build({key: key, title: title, depth: depth, order: order})
      unless toc.save
        return false
      end
      current_order += 1
    end
    true
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => [:write_handler, :remove_handler, :save_sp_preferences]

  def page_handler
    @wikipage = Wikipage.find_by_title(params[:wikipage])
    if @wikipage.nil?
      @wikipage = Wikipage.new({title: params[:wikipage], revision: 0})
    end

    unless params[:action].nil?
      case params[:action]
        when 'edit'
          return render 'home/edit'
        when 'history'
          @revisions = @wikipage.revisions.reorder('created_at desc').page(params[:page])
          return render '/home/revision_history'
        when 'setting'
        when 'revision'
          @revision = @wikipage.revision.where(revision: params[:id].to_i).first
          return render 'home/wikipage/wikipage_layout'
        else
          return render 'home/wikipage/wikipage_layout'
      end
    end
    render 'home/wikipage/wikipage_layout'
  end

  def write_handler
    # 빈 페이지 일 경우 페이지를 생성한다.

    # 페이지를 생성하기 전 validation 체크를 한다.

    # validation 체크 후 문제가 없다면 revision 을 생성한다. (before_save)

    # 저장 후에는 수정을 마친 페이지로 redirection 한다.
    title = params[:wikipage]
    body = params[:body]
    comment = params[:comment]
    user_id = current_user.nil? ? nil : current_user.id
    modifier = current_user.nil? ? nil : current_user.email

    @wikipage = Wikipage.find_by_title(title)
    if @wikipage.nil?
      @wikipage = Wikipage.new({title: title, body: body, comment: comment, user_id: user_id, modifier: modifier, revision: 1})
      unless @wikipage.save
        return render nothing: true, status: :internal_server_error
      end
    elsif @wikipage.body != params[:body] || @wikipage.comment != params[:comment]
      Wikipage.transaction do
        @wikipage.update_wikipage(params, current_user)
      end
    end

    redirect_to URI.encode('/' + params[:wikipage])
  end

  def update_handler
    render(status: :ok, nothing: true)
  end

  def remove_handler
    @wikipage = Wikipage.find_by_title(params[:wikipage])
    @wikipage.destroy
    if @wikipage.save
      return render nothing: true, status: :ok
    end
    render nothing: true, status: :internal_server_error
  end

  def root_handler
    redirect_to '/Home'
  end

  def changes
    @wikipages = Wikipage.limit(10).reorder('updated_at desc')
    render 'home/changes'
  end

  def searches
    @words = InvertedIndex.where("word = '#{params[:q]}'")
    render 'home/searches'
  end

  def preference
    @preference = current_user.preference
    render 'home/preference'
  end

  def save_sp_preferences
    title = params[:userpage_title]
    p = Preference.find_by_user_id(current_user.id)
    p = current_user.build_preference if p.nil?
    p.title = title
    p.email = current_user.email
    if p.save
      return redirect_to preference_path
    end
    render nothing: true, status: :internal_server_error
  end

  def sp_markdown
    render text: markdown_to_html(params[:text]), status: :ok
  end

  private
  def generalize_url

  end

end

app/views/home/wikipage/_header_titles.html.erb
<% titles = params[:wikipage].split(/\//); titles[0..-2].each_with_index do | item, index | %>
<span class="parent">
    <a href="<%= '/' + titles[0..index].join('/') %>"><%= titles[index] %></a><span class="small"> >> </span>
</span>
<% end %>
<span><%= titles[-1] %></span>
<a id="top" href="#top" class="caret-target vcaret">#</a>

app/views/home/wikipage/_section_body.html.erb
<% unless @revision.nil? %>
<div class="infobox message">
    <p>You are seeing an old version of the page. Go to <a href="<%= absolute_path(@wikipage) %>">latest version</a></p>
</div>
<% end %>

<% if @wikipage.body.blank? %>
    <p>This page is empty.</p>
<% elsif !@revision.nil? %>
    <div class="content"><%= markdown_to_html(@revision.body) %></div>
<% else %>
    <div class="content"><%= markdown_to_html(@wikipage.body) %></div>
<% end %>

app/views/home/wikipage/_section_similar_page.html.erb
<% unless @wikipage.similar_pages.blank? %>
<div class="border-row"></div>
<h3>Similar page</h3>
<ul>
    <% @wikipage.similar_pages.each do |similar_page| %>
        <li class="wikipage"><a href="<%= absolute_path(similar_page.title) %>"><%= similar_page.title  %></a></li>
    <% end %>
</ul>
<% end %>

app/views/home/wikipage/wikipage_layout.html.erb
<article>
    <header>
        <h1>
            <%= render partial: 'home/wikipage/header_titles' %>
            <a href="<%= searches_path + '?q=' + @wikipage.title %>" class="search-by-title"><small>Find similar titles</small></a>
        </h1>
        <ul class="info">
            <li class="updated_at">
                <% unless @wikipage.updated_at.nil? %>
                <span>Last modified at : <time><%= @wikipage.updated_at %></time></span>
                <% end %>

                <% unless @wikipage.revisions.nil? %>
                <a href="<%= absolute_path(@wikipage.title) + '?rev=list' %>">
                    (rev. <span class="revision"><%= params[:rev] ? params[:rev] : @wikipage.revision %></span>)
                </a>
                <% end %>
            </li>
            <% if admin?(current_user) || @wikipage.can_write?(current_user) %>
                <% if @revision.nil? %>
                    <li class="edit_menu">
                        <a href="<%= absolute_path(params[:wikipage]) %>?view=edit" id="edit" class='btn btn-primary'>Edit</a>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </header>
    <% unless @wikipage.tocs.nil? or @wikipage.tocs.blank? %>
        <section class="toc-section">
            <%= generate_toc_html(@wikipage) %>
        </section>
    <% end %>
    <section class="body">
        <%= render partial: 'home/wikipage/section_body' %>
    </section>

    <section class="similar_page">
        <%= render partial: 'home/wikipage/section_similar_page' %>
    </section>
</article>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>