config/routes.rb
EcogwikiRuby::Application.routes.draw do

  devise_for :users, skip: [:sessions, :passwords, :registrations]
  devise_scope :user do
    get '/sign_in', to: 'users/sessions#new', as: 'sign_in'
    post '/sign_in', to: 'users/sessions#create', as: 'sign_in'
    delete '/sign_out', to: 'users/sessions#destroy', as: 'sign_out'
  end

  get '/changes', to: 'home#sp_changes', as: 'changes'
  get '/searches', to: 'home#sp_searches', as: 'searches'
  get '/preference', to: 'home#sp_preferences', as: 'preference'
  post '/preferences', to: 'home#save_sp_preferences', as: 'preference'
  post '/helper/markdown', to: 'home#sp_markdown', as: 'helper_markdown'

  get '*wikipage', to: 'home#page_handler', as: 'wikipage', wikipage: /.+/
  post '*wikipage', to: 'home#write_handler', wikipage: /.+/
  put '*wikipage', to: 'home#update_handler', wikipage: /.+/
  delete '*wikipage', to: 'home#remove_handler', wikipage: /.+/
  root :to => 'home#root_handler'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>EcogwikiRuby</title>
    <%= stylesheet_link_tag    'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
<body data-controller="<%= params[:controller]%>" data-action="<%= params[:action] %>" data-view="<%= params[:view] %>">
    <div style="display: none;"><a href="#skip">Skip to content</a></div>
    <!--[if lt IE 9]>
    <h1>You Must Upgrade Your Browser</h1>
    <p>
        Using an outdated browser makes your computer unsafe. Find out what
        are the latest versions of the major browsers around from
        <a href="http://browsehappy.com/">Browse Happy</a>.

        You can also learn about alternative browsers that may fit you even
        better than the one you are currently using.
    </p>
    </div>
    <![endif]-->
    <%= 'current_user' %>
    <%= current_user.nil? %>
    <div class="top-bar">
        <ul>
            <li class="search">
                <%= form_tag('/sp.searches', method: 'get') do %>
                    <label style="display: none" for="searchbox">Search</label>
                    <input type="hidden" name="redir" value="1">
                    <input type="text" id="searchbox" placeholder="search" name="q" class="form-control">
                    <input type="submit">
                <% end %>
            </li>
            <li class="article-title">
            </li>
            <li class="article-header">
            </li>
            <li>
                <% if current_user.nil? %>
                    <span class="user-email"></span>
                    <a href="<%= sign_in_url %>">Login</a>
                <% else %>
                    <span class="user-email"><%= current_user.email %></span>
                    <a href="/sp.preferences" class="preferences">Preferences</a>
                    <a href="<%= sign_out_url %>" id="logout" data-method='delete'>Logout</a>
                <% end %>
            </li>
        </ul>
    </div>
<div class="contents">
    <nav>
        <ul>
            <li><a href="/Home" class="shortcut">Home</a></li>
            <li><a href="/sp.changes" class="shortcut">Changes</a></li>
        </ul>
    </nav>
    <div><a name="skip"></a></div>
    <%= yield %>
</div>
<input type="hidden" name="facebook-id" data-facebook-id="<%= facebook_id %>">
<div id="fb-root"></div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>